name: Infraestructure Deployment
on:
  push:
    branches: [ "main" ]
    paths:
      - 'infraestructure/**'


jobs:
  deploy:
    name: terraform setting
    runs-on: ubuntu-latest
    env:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
    - name: Check out of the repo
      uses: actions/checkout@v3
      
    - name: Terraform version
      run: terraform version
      
    - name: Terraform init
      run: terraform init -backend-config
      working-directory: infraestructure

    - name: Terraform validate
      run: terraform validate
      working-directory: infraestructure

    - name: Terraform plan
      run: terraform plan -var-file terraform.tfvars -out=plan.out
      working-directory: infraestructure

    - name: Apply Terraform
      run: terraform apply -var-file terraform.tfvars -auto-approve
      working-directory: infraestructure
